srsv2:
    image: "zhouweitong/srs-docker:latest"
    ports:
        - "443:443"
        - "1935:1935"
        - "1985:1985"
        - "8080:8080"
        - "8082:8082"
    volumes:
        - srs_data:/root/srs/trunk/objs/nginx